export const OPTIONS = [
    { "name": "Psychostick - ABCDEath", "url": "/psychostick/19-abcdeath" },
    { "name": "Psychostick - Bruce Campbell", "url": "/psychostick/bruce-campbell" },
    { "name": "Ween - Push Th Little Daisies", "url": "/ween/push-th-little-daisies" },
    { "name": "Ween - Captain", "url": "/ween/captain" },
    { "name": "Psychostick - Jagermeister Love Song", "url": "/psychostick/20-jagermeister-love-song" },
    { "name": "Psychostick - Obey The Beard", "url": "/psychostick/obey-the-beard" },
    { "name": "Ween - Ocean Man", "url": "/ween/ocean-man" },
    { "name": "Psychostick - Because Boobs", "url": "/psychostick/04-because-boobs" },
    { "name": "Ween - Joppa Road", "url": "/ween/joppa-road" },
    { "name": "Psychostick - Tuesday", "url": "/psychostick/tuesday" },
    { "name": "Psychostick - From the Heart (I Hate You)", "url": "/psychostick/from-the-heart-i-hate-you" },
    { "name": "Psychostick - BEER!!!", "url": "/psychostick/08-beer" },
    { "name": "Psychostick - Two Ton Paperweight", "url": "/psychostick/03-two-ton-paperweight" },
    { "name": "Ween - Tried And True", "url": "/ween/tried-and-true" },
    { "name": "Red Hot Chili Peppers - Give It Away", "url": "/red-hot-chili-peppers-official/give-it-away" },
    { "name": "Psychostick - Tuff Luv", "url": "/psychostick/tuff-luv" },
    { "name": "Belly -  Feed the Tree ", "url": "/bellyofficial/belly-feed-the-tree" },
    { "name": "Disturbed - Down with the Sickness", "url": "/disturbed1/down-with-the-sickness" },
    { "name": "Ween - Voodoo Lady", "url": "/ween/voodoo-lady" },
    { "name": "Ween - Zoloft", "url": "/ween/zoloft" },
    { "name": "Belly - Snow (Hey Oh)", "url": "/red-hot-chili-peppers-official/snow-hey-oh" },
    { "name": "Psychostick - This is Not a Song, It's a Sandwich", "url": "/psychostick/11-this-is-not-a-song-its-a" },
    { "name": "Psychostick - The Hunger Within", "url": "/psychostick/08-the-hunger-within" },
    { "name": "Psychostick - We Ran Out of CD Space", "url": "/psychostick/24-we-ran-out-of-cd-space" },
    { "name": "Psychostick - President Rhino", "url": "/psychostick/president-rhino" },
    { "name": "Ween - Among His Tribe", "url": "/ween/among-his-tribe" },
    { "name": "Ween - I Dont Want It", "url": "/ween/i-dont-want-it" },
    { "name": "Psychostick - Reading Rainbow Cover", "url": "/psychostick/reading-rainbow-cover" },
    { "name": "Red Hot Chili Peppers - Can't Stop", "url": "/red-hot-chili-peppers-official/cant-stop" },
    { "name": "Psychostick - Jolly Old Sadist", "url": "/psychostick/03-jolly-old-sadist" },
    { "name": "Ween - If You Could Save Yourself", "url": "/ween/if-you-could-save-yourself" },
    { "name": "Ween - Transdermal Celebration", "url": "/ween/transdermal-celebration" },
    { "name": "Ween - Happy Colored Marbles", "url": "/ween/happy-colored-marbles" },
    { "name": "Ween - Oh My Dear Falling In Love", "url": "/ween/oh-my-dear-falling-in-love" },
    { "name": "Black Sabbath - Iron Man (2012 - Remaster)", "url": "/blacksabbath/iron-man" },
    { "name": "Red Hot Chili Peppers - Under the Bridge", "url": "/red-hot-chili-peppers-official/under-the-bridge" },
    { "name": "Ween - Its Gonna Be A Long Night", "url": "/ween/its-gonna-be-a-long-night" },
    { "name": "Red Hot Chili Peppers - Californication", "url": "/red-hot-chili-peppers-official/californication" },
    { "name": "Ween - The Argus", "url": "/ween/the-argus" },
    { "name": "Ween - Hey There Fancypants", "url": "/ween/hey-there-fancypants" },
    { "name": "Ween - Mutilated Lips", "url": "/ween/mutilated-lips" },
    { "name": "Paramore - That's What You Get", "url": "/paramore/thats-what-you-get" },
    { "name": "Red Hot Chili Peppers - Dark Necessities", "url": "/red-hot-chili-peppers-official/dark-necessities" },
    { "name": "Ween - Dont Get 2 Close 2 My Fantasy", "url": "/ween/dont-get-2-close-2-my-fantasy" },
    { "name": "Ween - Baby Bitch", "url": "/ween/baby-bitch" },
    { "name": "Ween - Blue Balloon", "url": "/ween/blue-balloon" },
    { "name": "Ween - Bananas And Blow", "url": "/ween/bananas-and-blow" },
    { "name": "Ween - Chocolate Town", "url": "/ween/chocolate-town" },
    { "name": "Red Hot Chili Peppers - Otherside", "url": "/red-hot-chili-peppers-official/otherside" }
]
export const GUESSES = 6
export const TIMES = [2, 3, 5, 8, 12, 18]
export const MAX_TIME = TIMES[TIMES.length - 1]
